apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsq-vocprez-deployment
  labels:
    app: gsq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsq
  template:
    metadata:
      labels:
        app: gsq
    spec:
      containers:
      - name: gsq-vocprez
        image: 680471986828.dkr.ecr.ap-southeast-2.amazonaws.com/gsq/vocprez:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gsq-vocprez-service
spec:
  selector:
    app: gsq
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000